### ISSUE TITLE
This is 5 years out of sync with sourceforge

### ISSUE THREAD

**Issue by hjmjohnson** [Slicer/teem#6]
Are there instructions for how to merge this information with updates from sourceforge?

@jcfr

**Comment by hjmjohnson** [comment]
Not interested in pursuing this any longer.

**Comment by jcfr** [comment]
Thanks for the follow up :pray: 

There are no automated way to perform such updates, the main idea would be to create a new branch with a similar naming convention `slicer-YYYY-MM-DD-rNNNN`.

There also have been discussion to update teem itself & maintain it on GitHub. See https://github.com/Slicer/teem/pull/5

It may worth syncing with @kindlmann and see how we could move forward.

Related issues & discussions:
* https://github.com/Slicer/teem/pull/5
* https://www.slicer.org/wiki/Documentation/Labs/NrrdReading_Writing_Optimizations
* https://github.com/Slicer/Slicer/issues/3455
* http://teem.sourceforge.net/

cc: @lassoan @pieper @dzenanz

**Comment by kindlmann** [comment]
Can someone describe in more detail what about Teem needs syncing with Slicer?

The main thing I can think of is the Nrrd file read/write functionality, repackaged as "NrrdIO" for ITK.

In the last few weeks I've been doing Teem maintenance in preparation for another release (this may sound familiar to @pieper ). This has included cleaning up headers and code (removing needless globals), reformatting everything with clang-format, and creating new CFFI-based bindings for everything in Teem.  This is ongoing work, being committed to the most upstream source for Teem, on sourceforge (more reliable now than in the past).

Once that's done I'd be happy to work with someone on patching/reconciling changes that have been made to things downstream.

**Comment by jamesobutler** [comment]
Hi @kindlmann! Thanks for the continued maintenance of teem 🙏🏻 

Slicer maintains its own fork of teem here in GitHub that is actively incorporated into the [Slicer superbuild](https://github.com/Slicer/Slicer/blob/main/SuperBuild/External_teem.cmake) build process. It is currently using a version of teem from 2015 (https://github.com/Slicer/teem/commits/slicer-2015-04-14-r6245). From what I see at https://sourceforge.net/p/teem/code/HEAD/tree/teem/trunk/ Slicer is now out of sync (r6245 -> r6632) by almost 400 commits. To continue utilizing the latest of teem as it is continually maintained there is interest to get back in sync.

4 years ago there was discussion related to improvements to teem (see https://github.com/Slicer/teem/pull/5#issuecomment-435034503), but what prevented that collaboration was a decision to move teem onto GitHub as you mentioned in https://github.com/Slicer/teem/pull/5#issuecomment-427342484 (which appears to not have happened?). If there was an official teem repo in GitHub then it would be very easy for the Slicer organization to create a fork and stay in sync with the upstream with it being all on GitHub.

Would you be willing to move teem to GitHub? It appears that @hjmjohnson was enthusiastic to be able to help with this work (see https://github.com/Slicer/teem/pull/5#issuecomment-427382925). Other users, including myself, find sourceforge confusing to navigate compared to GitHub resulting in us less likely to use/contribute to the open source project. For me it is probably because I started coding around 2015 in college and I started with GitHub and that is all I know. Recent CS students I know have used GitHub exclusively though it appears you still use svn for your teachings. It would be greatly appreciated to continue the open source efforts of teem entirely on GitHub 🙏🏻

**Comment by dzenanz** [comment]
We would also like to update ITK's copy of `NrrdIO`, which is now 9 years old: https://github.com/InsightSoftwareConsortium/ITK/commits/master/Modules/ThirdParty/NrrdIO/src/NrrdIO

**Comment by jamesobutler** [comment]
@kindlmann Did my above answer clarify your question about the syncing issues between Slicer Teem and the official Teem repository?
